#!/usr/bin/env python

import csv
import sys
import time

for row in csv.reader(iter(sys.stdin.readline, '')):
    print(row)

def time_converter(time_in):
    # ISO-8601 format
    # convert from pst to est

def zipcode(zip_in):
    # All ZIP codes should be formatted as 5 digits. 
    # If there are less than 5 digits, assume 0 as the prefix.

def name(name_in):
    # The FullName column should be converted to uppercase. 
    # There will be non-English names.

def address(address_in):
    #  Unicode validation. 
    # there are commas in the Address field
    # your CSV parsing will need to take that into account. Commas will only be present inside a quoted string.

def duration(duration_in):
    # HH:MM:SS.MS format (where MS is milliseconds); 
    # convert to total number of seconds expressed as float
    # You should not round the result.

def total_duration(total_in):
    # sum of FooDuration and BarDuration

def notes(notes_in):
    # If there are invalid UTF-8 characters, please replace them with the Unicode Replacement Character.
